# Generated by Django 4.1.4 on 2023-01-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='student',
            field=models.ManyToManyField(to='grades.students'),
        ),
    ]
