# Generated by Django 4.1.4 on 2022-12-22 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fscohort', '0005_alter_student_options_alter_student_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='student_files'),
        ),
    ]
