# Generated by Django 4.1.4 on 2022-12-22 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='User',
            new_name='user',
        ),
    ]
