# Generated by Django 4.1.4 on 2022-12-27 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='prioirty',
            new_name='priority',
        ),
    ]
